### PR TITLE
View more card

### PR DESCRIPTION
**Pull request by psollars**
Adds in links to Facebook, Calendar and Google maps directions. Also toggles view more information and fixes the way that the description is displayed.

### CODE REVIEW

**Comment by psollars** [comment]
I did 'git merge master' before creating this PR so not sure why GitHub sees conflicts (I don't have local conflicts). Please review the code but I'm 99% sure we need everything that's on this view-more-card branch.

**Comment by slothwerks-studio** [comment]
Due to multiple users working on the same file, the index.css file is a bit of a mess and needs to be cleaned up (but we all knew that).  Will test post-merge and make sure the app still works.  External user feedback:  "Love the expanded details view.  Please make the icons larger.  The launch icon next to the address is unnecessary.  Add to calendar icons don't seem to do anything on my end.  After expanding the view, please place the directions icons under the address rather than all the way to the bottom of the expanded description."

**Comment by psollars** [comment]
There's a CSS error on master now... fixing.

**Comment by slothwerks-studio** [comment]
Meh - missed a bracket on the index.css file; pushed a quick fix directly to master branch to compensate.

**Pull request merged**
